# Generated by Django 5.0.1 on 2024-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz', '0002_car_radio_on_tz_car_use_tz_alter_car_numer_tz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='unit',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
