# Generated by Django 5.0.1 on 2024-03-21 11:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz', '0003_car_region_car_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='refit_tz',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='run_tz',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='seats_tz',
            field=models.IntegerField(default=False, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='car',
            name='sgu_tz',
            field=models.CharField(default='Не обладнано', max_length=20),
        ),
    ]
